agentName: aws_logs
agentType: integration
title: 'Forward AWS logs'
metaDescription: 'Forward logs from AWS'
introFilePath: 'src/install/aws_logs/intro.mdx'
appInfo: 
  - optionType: service
    label: 'What type of AWS service are you forwarding logs from?'
    placeholder: 'Choose one:'
    options: 
      - value: 'EC2'
        displayName: 'Amazon EC2'
      - value: 'EKS'
        displayName: 'Amazon EKS'
      - value: 'ECS'
        displayName: 'Amazon ECS'        
      - value: 'cloudfront'
        displayName: 'Amazon Cloudfront'
      - value: 'security_lake'
        displayName: 'Amazon Security Lake'    
  - optionType: forward_EC2
    label: 'How would you like to forward your EC2 logs?'
    placeholder: 'Choose one:'
    options: 
      - value: 'infra_fluentbit'
        displayName: 'Infrastructure agent with Fluentbit'
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function'
  - optionType: forward_EKS
    label: 'How would you like to forward your EKS logs?'
    placeholder: 'Choose one:'
    options: 
      - value: 'k8s_integration'
        displayName: 'Kubernetes integration'
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function'
  - optionType: forward_ECS
    label: 'How would you like to forward your ECS logs?'
    placeholder: 'Choose one:'
    options: 
      - value: 'infra_fluentbit'
        displayName: 'Infrastructure agent with Fluentbit'
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function' 
      - value: 'sidecar_firelens'                          
        displayName: 'Sidecar container with Firelens'
steps:
  - filePath: 'src/install/aws_logs/appInfo_service.mdx'
  - filePath: 'src/install/aws_logs/appInfo_EC2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'EC2'
  - filePath: 'src/install/aws_logs/appInfo_EKS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'EKS' 
  - filePath: 'src/install/aws_logs/appInfo_ECS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'ECS'    
  - filePath: 'src/install/aws_logs/cloudfront/intro_cloudfront.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'cloudfront'    
  - filePath: 'src/install/aws_logs/security_lake/intro_securitylake.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'security_lake'                  