agentName: docker-otel-host
agentType: integration
title: 'Monitor Docker containers with OpenTelemetry'
metaDescription: 'Send your Docker container metrics to New Relic using the OpenTelemetry Collector.'
introFilePath: 'src/install/docker-otel-host/intro.mdx'
appInfo: []
redirects:
  - /docs/infrastructure/host-integrations/host-integrations-list/docker-monitoring/otel-integration
steps:
  - filePath: 'src/install/docker-otel-host/host/prerequisites.mdx'
  - filePath: 'src/install/docker-otel-host/host/configure-collector.mdx'
  - filePath: 'src/install/docker-otel-host/collector/environment.mdx'
  - filePath: 'src/install/docker-otel-host/host/verify.mdx'
whatsNextFilePath: 'src/install/docker-otel-host/whatsNext.mdx'