agentName: jmx
agentType: integration
title: 'JMX monitoring integration'
metaDescription: 'Install the JMX integration'
introFilePath: 'src/install/jmx/intro.mdx'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration
  - /docs/jmx-monitoring-install
  - /docs/jmx-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-configuration
  - /docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-install/
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'     
      - value: 'ecs'
        displayName: 'ECS'
        logo: 'amazonECS'
      - value: 'kubernetes'
        displayName: 'Kubernetes'
        logo: 'k8'
  - optionType: deployment
    label: 'Choose your install path'
    placeholder: 'Choose one:'
    options:     
      - value: 'apt'
        displayName: 'Install using Apt (Debian, Ubuntu)'
      - value: 'yum'
        logo: 'linux'      
        displayName: 'Install using Yum (Amazon Linux, CentOS, RHEL)'
      - value: 'zypper'
        displayName: 'Install using Zypper (SLES)'
      - value: 'tar'
        displayName: 'Install from tarball (Other Linux distros)'  
        logo: 'linux'  


steps:
  - filePath: 'src/install/jmx/guided.mdx'
  - filePath: 'src/install/jmx/default-requirements.mdx'
    overrides: 
        - filePath: 'src/install/jmx/ecs/requirements-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
        - filePath: 'src/install/jmx/kubernetes/requirements-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'
  - filePath: 'src/install/jmx/install-infra.mdx'
  - filePath: 'src/install/jmx/linux/install-apt.mdx'
    overrides: 
        - filePath: 'src/install/jmx/linux/install-apt.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'apt' 
        - filePath: 'src/install/jmx/linux/install-yum.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'yum'
        - filePath: 'src/install/jmx/linux/install-tarball.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'tar'
        - filePath: 'src/install/jmx/linux/install-zypper.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'zypper'
  - filePath: 'src/install/jmx/linux/install-linux.mdx'
    overrides: 
        - filePath: 'src/install/jmx/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/jmx/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'           
        - filePath: 'src/install/jmx/ecs/install-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
        - filePath: 'src/install/jmx/kubernetes/install-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'  
  - filePath: 'src/install/jmx/find-data.mdx'
whatsNextFilePath: 'src/install/jmx/whatsNext.mdx'