agentName: nginx-otel-kubernetes
agentType: integration
title: 'Monitor NGINX on Kubernetes with OpenTelemetry'
metaDescription: 'Send your NGINX metrics and logs from Kubernetes to New Relic using the OpenTelemetry Collector.'
introFilePath: 'src/install/nginx-otel-kubernetes/intro.mdx'
appInfo: []
redirects:
  - /docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-otel-kubernetes
steps:
  - filePath: 'src/install/nginx-otel-kubernetes/kubernetes/prerequisites.mdx'
  - filePath: 'src/install/nginx-otel-kubernetes/kubernetes/install-collector.mdx'
  - filePath: 'src/install/nginx-otel-kubernetes/kubernetes/verify.mdx'
whatsNextFilePath: 'src/install/nginx-otel-kubernetes/whatsNext.mdx'
