agentName: nginx-otel-host
agentType: integration
title: 'Monitor self-hosted NGINX with OpenTelemetry'
metaDescription: 'Send your NGINX metrics and logs to New Relic using the OpenTelemetry Collector.'
introFilePath: 'src/install/nginx-otel-host/intro.mdx'
appInfo: []
redirects:
  - /docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-otel-host
steps:
  - filePath: 'src/install/nginx-otel-host/host/prerequisites-opensource.mdx'
  - filePath: 'src/install/nginx-otel-host/host/enable-status-opensource.mdx'
  - filePath: 'src/install/nginx-otel-host/host/configure-collector-opensource.mdx'
  - filePath: 'src/install/nginx-otel-host/collector/environment.mdx'
  - filePath: 'src/install/nginx-otel-host/logs/forwarding-opensource.mdx'
  - filePath: 'src/install/nginx-otel-host/host/verify.mdx'
whatsNextFilePath: 'src/install/nginx-otel-host/whatsNext.mdx'
