agentName: nginx-plus-otel
agentType: integration
title: 'Monitor self-hosted NGINX Plus with OpenTelemetry'
metaDescription: 'Send your NGINX Plus metrics to New Relic using the OpenTelemetry contirb collector.'
introFilePath: 'src/install/nginx-plus-otel/intro.mdx'
appInfo: []
redirects:
  - /docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-plus-otel
steps:
  - filePath: 'src/install/nginx-plus-otel/host/prerequisites-plus.mdx'
  - filePath: 'src/install/nginx-plus-otel/host/enable-status-plus.mdx'
  - filePath: 'src/install/nginx-plus-otel/host/configure-collector-plus.mdx'
  - filePath: 'src/install/nginx-plus-otel/collector/environment.mdx'
  - filePath: 'src/install/nginx-plus-otel/logs/forwarding-plus.mdx'
  - filePath: 'src/install/nginx-plus-otel/host/verify.mdx'
whatsNextFilePath: 'src/install/nginx-plus-otel/whatsNext.mdx'
