agentName: nginx-otel
agentType: integration
title: 'NGINX OpenTelemetry collector'
metaDescription: 'Install the NGINX OpenTelemetry collector'
introFilePath: 'src/install/nginx-otel/intro.mdx'
appInfo:
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options:
      - value: 'host'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'kubernetes'
        displayName: 'Kubernetes'
        logo: 'k8'
  - optionType: deployment
    label: ''
    placeholder: "Choose one:"
    options:
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true
      - value: "yum"
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        logo: 'linux'
        recommendedGuided: true
  - optionType: nginx_type
    label: ''
    placeholder: "Choose one:"
    options:
      - value: "opensource"
        displayName: "NGINX Open Source"
        recommendedGuided: true
      - value: "plus"
        displayName: "NGINX Plus"
        recommendedGuided: true

steps:
  - filePath: 'src/install/nginx-otel/appInfo.mdx'
  - filePath: 'src/install/nginx-otel/host/choose-install.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/host/prerequisites.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/host/enable-status-select.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/host/enable-status.mdx'
    overrides:
      - filePath: 'src/install/nginx-otel/host/enable-status-opensource.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
          - optionType: nginx_type
            options:
              - value: 'opensource'
      - filePath: 'src/install/nginx-otel/host/enable-status-plus.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
          - optionType: nginx_type
            options:
              - value: 'plus'
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/host/license.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/host/install-collector.mdx'
    overrides:
      - filePath: 'src/install/nginx-otel/host/install-collector-apt.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
          - optionType: deployment
            options:
              - value: 'apt'
      - filePath: 'src/install/nginx-otel/host/install-collector-yum.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
          - optionType: deployment
            options:
              - value: 'yum'
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/host/configure-collector.mdx'
    overrides:
      - filePath: 'src/install/nginx-otel/host/configure-collector-opensource.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
          - optionType: nginx_type
            options:
              - value: 'opensource'
      - filePath: 'src/install/nginx-otel/host/configure-collector-plus.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
          - optionType: nginx_type
            options:
              - value: 'plus'
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/collector/environment.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/logs/forwarding.mdx'
    overrides:
      - filePath: 'src/install/nginx-otel/logs/forwarding-opensource.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
          - optionType: nginx_type
            options:
              - value: 'opensource'
      - filePath: 'src/install/nginx-otel/logs/forwarding-plus.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
          - optionType: nginx_type
            options:
              - value: 'plus'
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/host/verify.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'host'
  - filePath: 'src/install/nginx-otel/kubernetes/prerequisites.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'kubernetes'
  - filePath: 'src/install/nginx-otel/kubernetes/status-endpoint.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'kubernetes'
  - filePath: 'src/install/nginx-otel/kubernetes/license.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'kubernetes'
  - filePath: 'src/install/nginx-otel/kubernetes/prepare-values.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'kubernetes'
  - filePath: 'src/install/nginx-otel/kubernetes/secret.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'kubernetes'
  - filePath: 'src/install/nginx-otel/kubernetes/deploy.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'kubernetes'
  - filePath: 'src/install/nginx-otel/kubernetes/verify.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'kubernetes'
whatsNextFilePath: 'src/install/nginx-otel/whatsNext.mdx'
