agentName: npm
agentType: integration
title: 'Network security prerequisites'
metaDescription: 'Network monitoring prerequisites'
introFilePath: 'src/install/npm/intro.mdx'
appInfo: 
  - optionType: region
    label: ''
    placeholder: 'Select your region'
    options: 
      - value: 'us'
        displayName: 'US'
        recommendedGuided: true
      - value: 'usFedramp'
        displayName: 'US Fedramp'
      - value: 'eu'
        displayName: 'EU'
  - optionType: installation
    label: ''
    placeholder: 'Select your installation method'
    options: 
      - value: 'docker'
        displayName: 'Docker'
        recommendedGuided: true
        logo: 'docker'
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
  - optionType: network
    label: ''
    placeholder: 'Select your network data type'
    options: 
      - value: 'snmp'
        displayName: 'SNMP'
        recommendedGuided: true
      - value: 'flow'
        displayName: 'Network flow'
      - value: 'syslog'
        displayName: 'Network syslog'

steps:
  - filePath: 'src/install/npm/appInfo.mdx'
  - filePath: 'src/install/npm/snmp/docker-us.mdx'
    overrides:
    # SNMP EU Docker 
    - filePath: 'src/install/npm/snmp/docker-eu.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'eu'
        - optionType: installation
          options: 
            - value: 'docker'
        - optionType: network
          options: 
            - value: 'snmp'
    # SNMP US Linux
    - filePath: 'src/install/npm/snmp/linux-us.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'us'
            - value: 'usFedramp'
        - optionType: installation
          options: 
            - value: 'linux'
        - optionType: network
          options: 
            - value: 'snmp'
    #SNMP EU Linux
    - filePath: 'src/install/npm/snmp/linux-eu.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'eu'
        - optionType: installation
          options: 
            - value: 'linux'
        - optionType: network
          options: 
            - value: 'snmp'
    # Network flow EU docker
    - filePath: 'src/install/npm/network-flow/docker-eu.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'eu'
        - optionType: installation
          options: 
            - value: 'docker'
        - optionType: network
          options: 
            - value: 'flow'
    # Network flow US docker
    - filePath: 'src/install/npm/network-flow/docker-us.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'us'
            - value: 'usFedramp'
        - optionType: installation
          options: 
            - value: 'docker'
        - optionType: network
          options: 
            - value: 'flow'
    # Network flow EU linux
    - filePath: 'src/install/npm/network-flow/linux-eu.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'eu'
        - optionType: installation
          options: 
            - value: 'linux'
        - optionType: network
          options: 
            - value: 'flow'
    # Network flow US linux
    - filePath: 'src/install/npm/network-flow/linux-us.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'us'
            - value: 'usFedramp'
        - optionType: installation
          options: 
            - value: 'linux'
        - optionType: network
          options: 
            - value: 'flow'
    #Syslog EU Docker
    - filePath: 'src/install/npm/syslog/docker-eu.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'eu'
        - optionType: installation
          options: 
            - value: 'docker'
        - optionType: network
          options: 
            - value: 'syslog'
    #Syslog US Docker
    - filePath: 'src/install/npm/syslog/docker-us.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'us'
        - optionType: installation
          options: 
            - value: 'docker'
        - optionType: network
          options: 
            - value: 'syslog'
    #Syslog US Fedramp Docker
    - filePath: 'src/install/npm/syslog/docker-us-fedramp.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'usFedramp'
        - optionType: installation
          options: 
            - value: 'docker'
        - optionType: network
          options: 
            - value: 'syslog'
    #Syslog US Fedramp Linux
    - filePath: 'src/install/npm/syslog/docker-us-fedramp.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'usFedramp'
        - optionType: installation
          options: 
            - value: 'linux'
        - optionType: network
          options: 
            - value: 'syslog'
    #Syslog US Linux
    - filePath: 'src/install/npm/syslog/linux-us.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'us'
        - optionType: installation
          options: 
            - value: 'linux'
        - optionType: network
          options: 
            - value: 'syslog'
    #Syslog EU Linux
    - filePath: 'src/install/npm/syslog/linux-eu.mdx'
      selectedOptions: 
        - optionType: region
          options: 
            - value: 'eu'
        - optionType: installation
          options: 
            - value: 'linux'
        - optionType: network
          options: 
            - value: 'syslog'
  - filePath: 'src/install/npm/whats-next-default.mdx'
    overrides:
    # SNMP 
    - filePath: 'src/install/npm/snmp/whats-next.mdx'
      selectedOptions: 
        - optionType: network
          options: 
            - value: 'snmp'
    # Network flow 
    - filePath: 'src/install/npm/network-flow/whats-next.mdx'
      selectedOptions: 
        - optionType: network
          options: 
            - value: 'flow'
    # Network syslog 
    - filePath: 'src/install/npm/syslog/whats-next.mdx'
      selectedOptions: 
        - optionType: network
          options: 
            - value: 'syslog'
