title: Security
path: /docs/security
pages:
  - title: Overview
    path: /docs/security
  - title: Security and Privacy
    pages:
      - title: Data privacy
        pages:
          - title: Data privacy
            path: /docs/security/security-privacy/data-privacy/data-privacy-new-relic
          - title: Personal data requests
            path: /docs/security/security-privacy/data-privacy/new-relic-personal-data-requests
          - title: Security controls for privacy
            path: /docs/security/security-privacy/data-privacy/security-controls-privacy
      - title: Compliance
        pages:
          - title: Data encryption
            path: /docs/security/security-privacy/compliance/data-encryption
          - title: Encryption key management
            path: /docs/security/security-privacy/compliance/key-management-encryption-rest
          - title: FedRAMP-compliant endpoints
            path: /docs/security/security-privacy/compliance/fedramp-compliant-endpoints
          - title: 'Certifications, Standards and Regulations'
            pages:
              - title: 'Introduction to certificates, standards, and regulations'
                path: /docs/security/security-privacy/compliance/regulatory-audits-new-relic-services
              - title: FedRAMP Moderate
                path: /docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp-moderate
              - title: HIPAA
                path: /docs/security/security-privacy/compliance/certificates-standards-regulations/hipaa
              - title: ISO
                path: /docs/security/security-privacy/compliance/certificates-standards-regulations/iso
              - title: SOC 2
                path: /docs/security/security-privacy/compliance/certificates-standards-regulations/soc2
              - title: TISAX
                path: /docs/security/security-privacy/compliance/certificates-standards-regulations/tisax
          - title: HIPAA enablement - what you need to know
            path: /docs/security/security-privacy/compliance/hipaa-readiness-new-relic
      - title: Information security
        pages:
          - title: Report security vulnerabilities
            path: /docs/security/security-privacy/information-security/report-security-vulnerabilities-hackerone
          - title: Software Development Lifecycle
            path: /docs/security/security-privacy/information-security/software-development-lifecycle
          - title: Security bulletins
            path: /docs/security/security-privacy/information-security/security-bulletins
      - title: Security bulletins
        pages:
          - title: 'Apache Log4j - CPM, NR21-04'
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr21-04
          - title: 'Apache Log4j - Java, NR21-03'
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr21-03
          - title: NR21-02
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr21-02
          - title: NR21-01
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr21-01
          - title: SolarWinds Orion
            path: /docs/security/new-relic-security/security-bulletins/solarwinds-orion
          - title: COVID-19
            path: /docs/security/new-relic-security/security-bulletins/covid-19
          - title: NR20-02
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr20-02
          - title: NR20-01
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr20-01
          - title: NR19-05
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr19-05
          - title: NR19-04
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr19-04
          - title: NR19-03
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr19-03
          - title: NR19-02
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr19-02
          - title: NR19-01
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr19-01
          - title: NR18-12
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-12
          - title: NR18-11
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-11
          - title: NR18-10
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-10
          - title: NR18-09
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-09
          - title: NR18-08
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-08
          - title: NR18-07
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-07
          - title: NR18-06
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-06
          - title: NR18-05
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-05
          - title: NR18-04
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-04
          - title: NR18-03
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-03
          - title: NR18-02
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-02
          - title: NR18-01
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr18-01
          - title: NR17-06
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr17-06
          - title: NR17-05
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr17-05
          - title: NR17-04
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr17-04
          - title: NR17-03
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr17-03
          - title: NR17-02
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr17-02
          - title: NR17-01
            path: /docs/security/new-relic-security/security-bulletins/security-bulletin-nr17-01
          - title: Notification of Apollo.io security incident
            path: /docs/security/new-relic-security/security-bulletins/notification-apolloio-security-incident
          - title: Heartbleed
            path: /docs/security/new-relic-security/security-bulletins/security-heartbleed-vulnerability
