title: Workflow Automation
path: /docs/workflow-automation
pages:
  - title: Introduction to workflow automation
    path: /docs/workflow-automation/introduction-to-workflow
  - title: Setup and configuration
    path: /docs/workflow-automation/setup-and-configuration
    pages:
      - title: Set up AWS credentials
        path: /docs/workflow-automation/setup-and-configuration/set-up-aws-credentials
      - title: Create destinations and notifications
        path: /docs/workflow-automation/setup-and-configuration/create-destinations
      - title: Actions catalog
        path: /docs/workflow-automation/setup-and-configuration/actions-catalog
        pages:
          - title: Actions catalog overview
            path: /docs/workflow-automation/setup-and-configuration/actions-catalog/actions-catalog
          - title: AWS actions
            path: /docs/workflow-automation/setup-and-configuration/actions-catalog/aws
          - title: HTTP actions
            path: /docs/workflow-automation/setup-and-configuration/actions-catalog/http
          - title: New Relic actions
            path: /docs/workflow-automation/setup-and-configuration/actions-catalog/new-relic
          - title: Communication actions
            path: /docs/workflow-automation/setup-and-configuration/actions-catalog/communication
          - title: PagerDuty actions
            path: /docs/workflow-automation/setup-and-configuration/actions-catalog/pagerduty
  - title: Create a workflow automation
    path: /docs/workflow-automation/create-a-workflow-automation
    pages:
      - title: Use a template
        path: /docs/workflow-automation/create-a-workflow-automation/use-a-template
      - title: Create your own workflow
        path: /docs/workflow-automation/create-a-workflow-automation/create-your-own
      - title: Start and schedule workflows
        path: /docs/workflow-automation/create-a-workflow-automation/start-schedule
      - title: Manage workflows
        path: /docs/workflow-automation/create-a-workflow-automation/managing-workflow
  - title: Workflow examples
    path: /docs/workflow-automation/workflow-examples
  - title: Troubleshooting
    path: /docs/workflow-automation/troubleshooting
  - title: Best practices and limits
    path: /docs/workflow-automation/limitations-and-faq
    pages:
      - title: Best practices
        path: /docs/workflow-automation/limitations-and-faq/workflow-best-practices
      - title: Workflow limits
        path: /docs/workflow-automation/limitations-and-faq/workflow-limits
  - title: Workflow automation APIs
    path: /docs/workflow-automation/workflow-automation-apis
    pages:
      - title: API guide
        path: /docs/workflow-automation/workflow-automation-apis/using-workflow-automation-api
      - title: CreateWorkflowDefinition
        path: /docs/workflow-automation/workflow-automation-apis/create-workflow-definition
      - title: UpdateWorkflowDefinition
        path: /docs/workflow-automation/workflow-automation-apis/update-workflow-definition
      - title: DeleteWorkflowDefinition
        path: /docs/workflow-automation/workflow-automation-apis/delete-workflow-definition
      - title: ValidateWorkflowDefinition
        path: /docs/workflow-automation/workflow-automation-apis/validate-workflow-definition
      - title: GetWorkflowDefinition
        path: /docs/workflow-automation/workflow-automation-apis/get-workflow-definition
      - title: GetWorkflowDefinitions
        path: /docs/workflow-automation/workflow-automation-apis/get-workflow-definitions
      - title: GetActionDefinitions
        path: /docs/workflow-automation/workflow-automation-apis/get-action-definitions
      - title: StartWorkflowRun
        path: /docs/workflow-automation/workflow-automation-apis/start-workflow-run
      - title: StopWorkflowRun
        path: /docs/workflow-automation/workflow-automation-apis/stop-workflow-run
      - title: SignalWorkflowRun
        path: /docs/workflow-automation/workflow-automation-apis/signal-workflow-run
      - title: CreateSchedule
        path: /docs/workflow-automation/workflow-automation-apis/create-schedule
      - title: GetSchedule
        path: /docs/workflow-automation/workflow-automation-apis/get-schedule
      - title: GetSchedules
        path: /docs/workflow-automation/workflow-automation-apis/get-schedules
      - title: DeleteSchedule
        path: /docs/workflow-automation/workflow-automation-apis/delete-schedule
      - title: Definition schema
        path: /docs/workflow-automation/workflow-automation-apis/definition-schema
