name: Auto-triage PRs to project boards

on:
  pull_request_target:
    types: [opened, labeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COLUMN_NAME: Needs Triage # column where issues will be created

jobs:
  content_project:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: 11873277
      PROJECT_NAME: Docs PRs and Issues
    name: Triage to Content Project
    steps:
    - name: Triages NEW issues and NEW pull requests to the Content Project
      if: github.event.action == 'opened'
      run: |
        HEADER="Accept: application/vnd.github.inertia-preview+json"
        PR_ID=${{ github.event.pull_request.id }}
        COLUMN=$(gh api -H "$HEADER" projects/$PROJECT_ID/columns --jq ".[] | select(.name == \"$COLUMN_NAME\").id")
        gh api -H "$HEADER" -X POST projects/columns/$COLUMN/cards -f content_type='PullRequest' -F content_id=$PR_ID

  localization_project:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: 12004783
      PROJECT_NAME: Docs Site Localization PRs and Issues
    name: Triage to Localization Project
    steps:
    - name: Triages NEW issues and NEW pull requests to the Localization Project
      if: |
        github.event.action == 'labeled' &&
        contains(github.event.pull_request.labels.*.name, 'localization')
      run: |
        HEADER="Accept: application/vnd.github.inertia-preview+json"
        PR_ID=${{ github.event.pull_request.id }}
        COLUMN=$(gh api -H "$HEADER" projects/$PROJECT_ID/columns --jq ".[] | select(.name == \"$COLUMN_NAME\").id")
        gh api -H "$HEADER" -X POST projects/columns/$COLUMN/cards -f content_type='PullRequest' -F content_id=$PR_ID

